name: Prod
on:
  push:
    branches:
      - main
    paths:
      - infrastructure/**
      - v1/**
jobs:
  build:
    name: Build & Deploy
    uses: ./.github/workflows/build_deploy.yaml
    permissions:
      id-token: write
      contents: read
      packages: read
    with:
      environment: prod
